version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/dotodo
      - MODEL_PARSE_URL=http://localhost:8001/parse
      - MODEL_RECO_URL=http://localhost:8002/recommend
    volumes:
      - ./backend/app:/app/app

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dotodo  # ← 여기도 변경
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: